from __future__ import annotations

from collections.abc import Iterator
from pathlib import Path
from threading import Event
from typing import Protocol

from .models import (
    CameraCapabilities,
    CameraDescriptor,
    CameraEvent,
    CameraInfo,
    CameraStatus,
    FileNamingField,
    FileNamingState,
    FocusResult,
    LiveViewMagnificationResult,
    LiveViewStartRequest,
    MediaItem,
)


class CameraEngineSession(Protocol):
    engine_name: str
    camera: CameraDescriptor

    def close(self) -> None: ...

    def info(self) -> CameraInfo: ...

    def status(self) -> CameraStatus: ...

    def capabilities(self) -> CameraCapabilities: ...

    def poll_event(self) -> CameraEvent: ...

    def stop_event_polling(self) -> None: ...

    def set_setting(self, key: str, value: str) -> CameraStatus: ...

    def sync_camera_clock(self) -> CameraStatus: ...

    def create_directory(self, name: str) -> str: ...

    def set_file_naming(self, field: FileNamingField, value: str) -> FileNamingState: ...

    def clean_sensor(self, auto_power_off: bool) -> None: ...

    def sleep_camera(self) -> None: ...

    def capture_still(self) -> CameraStatus: ...

    def start_bulb_exposure(self) -> CameraStatus: ...

    def stop_bulb_exposure(self) -> CameraStatus: ...

    def autofocus(self) -> CameraStatus: ...

    def half_press_shutter(self) -> CameraStatus: ...

    def start_recording(self) -> CameraStatus: ...

    def stop_recording(self) -> CameraStatus: ...

    def drive_focus(self, direction: str, step: str) -> FocusResult: ...

    def tap_focus(self, x: float, y: float) -> FocusResult: ...

    def click_white_balance(self, x: float, y: float) -> CameraStatus: ...

    def start_live_view(self, request: LiveViewStartRequest) -> None: ...

    def stop_live_view(self) -> None: ...

    def set_live_view_magnification(self, value: int) -> LiveViewMagnificationResult: ...

    def live_view_frame(self) -> bytes: ...

    def list_media(self) -> list[MediaItem]: ...

    def media_thumbnail(self, media_id: str) -> tuple[bytes, str]: ...

    def media_preview(self, media_id: str) -> tuple[bytes, str]: ...

    def download_media(self, media_id: str) -> tuple[MediaItem, Iterator[bytes]]: ...

    def upload_media(
        self,
        filename: str,
        source: Path,
        size_bytes: int,
        content_type: str,
        cancelled: Event | None = None,
    ) -> MediaItem: ...

    def media_info(self, media_id: str) -> MediaItem: ...

    def set_media_protection(self, media_id: str, enabled: bool) -> MediaItem: ...

    def set_media_rating(self, media_id: str, value: int) -> MediaItem: ...

    def set_media_rotation(self, media_id: str, degrees: int) -> MediaItem: ...

    def delete_media(self, media_id: str) -> None: ...


class CameraEngine(Protocol):
    name: str

    def health(self) -> tuple[bool, str | None, str | None]: ...

    def discover(self) -> list[CameraDescriptor]: ...

    def open(self, camera_id: str | None = None, profile_hint: str | None = None) -> CameraEngineSession: ...


class NetworkCameraEngine(Protocol):
    name: str

    def health(self) -> tuple[bool, str | None, str | None]: ...

    def open_connection(
        self,
        base_url: str,
        username: str = "",
        password: str = "",
    ) -> CameraEngineSession: ...
