package dev.openeos.control.ui

import dev.openeos.control.data.CameraCapabilities
import dev.openeos.control.data.CameraFeature
import dev.openeos.control.data.CameraInfo
import dev.openeos.control.data.CameraMediaItem
import dev.openeos.control.data.CameraProfile
import dev.openeos.control.data.CameraSettingControl
import dev.openeos.control.data.CameraStatus
import dev.openeos.control.data.CapabilityMatrix
import dev.openeos.control.data.ExposureState
import dev.openeos.control.data.LiveViewCapabilities

internal fun CameraUiState.withOfflinePreview(): CameraUiState = copy(
    previewMode = true,
    transport = null,
    info = CameraInfo(
        connected = true,
        model = CameraProfile.R6_MARK_III.modelName,
        serial = "offline-preview",
        api = "offline-preview",
    ),
    status = CameraStatus(
        connected = true,
        batteryLevel = 82,
        batteryStatus = "preview",
        recording = false,
        mode = "photo",
        mediaAvailable = true,
        remainingMinutes = 118,
        exposure = ExposureState(
            iso = "800",
            shutter = "1/125",
            aperture = "2.8",
            whiteBalance = "auto",
        ),
        storageTotalBytes = 128_000_000_000,
        storageFreeBytes = 84_000_000_000,
        storageFreeImages = 2_418,
        storageDeviceCount = 2,
        recordableShots = 2_418,
        remainingRecordingSeconds = 7_080,
    ),
    capabilities = CameraCapabilities(
        iso = listOf("Auto", "100", "200", "400", "800", "1600", "3200", "6400", "12800"),
        shutter = listOf("1/30", "1/50", "1/60", "1/100", "1/125", "1/250", "1/500", "1/1000"),
        aperture = listOf("1.8", "2.0", "2.8", "4.0", "5.6", "8.0", "11"),
        whiteBalance = listOf("auto", "daylight", "shade", "cloudy", "tungsten", "fluorescent", "flash"),
        advancedSettings = listOf(
            CameraSettingControl("moviemode", "Movie mode", "off", listOf("off", "on")),
            CameraSettingControl("shootingmode", "Shooting mode", "Manual", listOf("P", "TV", "AV", "Manual", "Bulb", "Movie", "Fv")),
            CameraSettingControl("exposurecompensation", "Exposure compensation", "0", listOf("-1", "-0.6", "-0.3", "0", "0.3", "0.6", "1")),
            CameraSettingControl("colortemperature", "Color temperature", "5200", listOf("2500", "3200", "4000", "5200", "5600", "6500", "10000")),
            CameraSettingControl("whitebalanceadjusta", "White balance shift A", "0", (-9..9).map(Int::toString)),
            CameraSettingControl("whitebalanceadjustb", "White balance shift B", "0", (-9..9).map(Int::toString)),
            CameraSettingControl("colorspace", "Color space", "sRGB", listOf("sRGB", "AdobeRGB")),
            CameraSettingControl("aspectratio", "Aspect ratio", "3:2", listOf("3:2", "1:1", "4:3", "16:9", "1.6x")),
            CameraSettingControl("zoom", "Zoom", "50", (0..100).map(Int::toString)),
            CameraSettingControl("soundrecording", "Sound recording", "manual", listOf("auto", "manual", "disable")),
            CameraSettingControl("soundrecordinglevel", "Sound recording level", "32", (0..63).map(Int::toString)),
            CameraSettingControl("windfilter", "Wind filter", "auto", listOf("auto", "enable", "disable")),
            CameraSettingControl("attenuator", "Attenuator", "disable", listOf("enable", "disable", "auto", "manual")),
            CameraSettingControl("focusbracketing", "Focus bracketing", "disable", listOf("enable", "disable")),
            CameraSettingControl("focusbracketingnumberofshots", "Focus bracketing shots", "100", (2..999).map(Int::toString)),
            CameraSettingControl("focusbracketingfocusincrement", "Focus increment", "4", (1..10).map(Int::toString)),
            CameraSettingControl("focusbracketingexposuresmoothing", "Exposure smoothing", "disable", listOf("enable", "disable")),
            CameraSettingControl("highframerate", "High frame rate", "disable", listOf("enable", "disable")),
            CameraSettingControl("moviecropping", "Movie cropping", "disable", listOf("enable", "disable")),
            CameraSettingControl("movieformat", "Movie recording format", "mp4", listOf("raw", "mp4")),
            CameraSettingControl("zoomspeed", "Power zoom speed", "8", (1..15).map(Int::toString)),
            CameraSettingControl("autopoweroff", "Auto power off", "30 seconds", listOf("15 seconds", "30 seconds", "1 minute", "3 minutes", "5 minutes", "10 minutes", "30 minutes", "Disable")),
            CameraSettingControl("capturetarget", "Capture target", "Phone", listOf("Phone", "Memory card")),
            CameraSettingControl("capturestorage", "Recording card", "CFe", listOf("CFe", "SD")),
            CameraSettingControl("cardselectionstillimage", "Still-image card", "card1", listOf("none", "card1", "card2")),
            CameraSettingControl("cardselectionmovie", "Movie card", "card2", listOf("none", "card1", "card2")),
            CameraSettingControl("afmethod", "AF method", "WholeAreaAF", listOf("LiveSpotAF", "FlexibleZoneAF1", "WholeAreaAF")),
            CameraSettingControl("afoperation", "AF operation", "AI Servo", listOf("One Shot", "AI Servo", "AI Focus")),
            CameraSettingControl("continuousaf", "Continuous AF", "On", listOf("Off", "On")),
            CameraSettingControl("drivemode", "Drive mode", "Super high speed continuous shooting", listOf("Single", "Continuous high speed", "Super high speed continuous shooting")),
            CameraSettingControl("meteringmode", "Metering", "Evaluative", listOf("Evaluative", "Partial", "Spot", "Center-weighted average")),
            CameraSettingControl("highisonr", "High ISO noise reduction", "Off", listOf("Off", "Low", "Normal", "High")),
            CameraSettingControl("alomode", "Auto Lighting Optimizer", "Standard", listOf("Standard", "Low", "High", "Off")),
            CameraSettingControl("aeb", "Auto exposure bracketing", "off", listOf("off", "+/- 1/3", "+/- 2/3", "+/- 1", "+/- 2", "+/- 3")),
            CameraSettingControl("picturestyle", "Picture style", "Auto", listOf("Auto", "Standard", "Portrait", "Fine detail")),
            CameraSettingControl("stillimagequality", "Image quality", "RAW", listOf("Large Fine JPEG", "cRAW + Large Fine JPEG", "RAW")),
            CameraSettingControl(
                "moviequality",
                "Movie quality",
                "3840x2160_5994_ipb_standard",
                listOf("3840x2160_5994_ipb_standard", "1920x1080_2997_ipb_standard"),
            ),
            CameraSettingControl("movieservoaf", "Movie Servo AF", "On", listOf("Off", "On")),
        ),
        matrix = CapabilityMatrix.ccapiNetwork(
            supported = setOf(
                CameraFeature.CAMERA_IDENTITY,
                CameraFeature.BATTERY_STATUS,
                CameraFeature.STORAGE_STATUS,
                CameraFeature.RECORDABLE_STATUS,
                CameraFeature.LIVE_VIEW,
                CameraFeature.LIVE_VIEW_JPEG_POLLING,
                CameraFeature.LIVE_VIEW_MAGNIFICATION,
                CameraFeature.STILL_CAPTURE,
                CameraFeature.BULB_EXPOSURE,
                CameraFeature.AUTOFOCUS,
                CameraFeature.SHUTTER_HALF_PRESS,
                CameraFeature.MOVIE_MODE_CONTROL,
                CameraFeature.FOCUS_DRIVE,
                CameraFeature.VIDEO_RECORDING,
                CameraFeature.TAP_FOCUS,
                CameraFeature.CLICK_WHITE_BALANCE,
                CameraFeature.EXPOSURE_CONTROL,
                CameraFeature.WHITE_BALANCE_CONTROL,
                CameraFeature.ZOOM_CONTROL,
                CameraFeature.SOUND_RECORDING_CONTROL,
                CameraFeature.SOUND_RECORDING_LEVEL_CONTROL,
                CameraFeature.FOCUS_BRACKETING_CONTROL,
                CameraFeature.MOVIE_SETTINGS_CONTROL,
                CameraFeature.CARD_SELECTION_CONTROL,
                CameraFeature.ADVANCED_SETTINGS,
                CameraFeature.MEDIA_BROWSER,
                CameraFeature.MEDIA_DOWNLOAD,
                CameraFeature.MEDIA_DELETE,
            ),
        ),
        liveView = LiveViewCapabilities.ccapiNetwork(),
        profile = CameraProfile.R6_MARK_III,
    ),
    mediaItems = listOf(
        CameraMediaItem("preview-001", "R6M3_0001.CR3", "raw", 31_457_280, "2026-07-21T10:08:24+08:00", true),
        CameraMediaItem("preview-002", "R6M3_0001.JPG", "image", 8_912_384, "2026-07-21T10:08:24+08:00", true),
        CameraMediaItem("preview-003", "R6M3_0002.MP4", "video", 128_450_560, "2026-07-21T10:10:02+08:00"),
    ),
    mediaThumbnails = emptyMap(),
    mediaThumbnailLoadingIds = emptySet(),
    liveViewFrameUrl = null,
    liveViewBitmap = null,
    liveViewDiagnostics = LiveViewDiagnostics(),
    operatorConfirmedFeatures = emptySet(),
    uiMode = UiMode.CONTROL,
    activeSettingPicker = null,
    error = null,
    errorOperation = null,
)
